### ISSUE TITLE
Print (pdf) whole IG

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/ig-template-base#151]
some mechanism to create a PDF of the whole IG. This is often needed by regulations or business policy. 

see chat discussion https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/printing.20IG.20pages

**Comment by lmckenzi** [comment]
In discussion w/ @JohnMoehrke, he indicated that the main use-case (be able to archive a frozen version of the spec) can be managed using the zips.  It's also possible to print to PDF or use 3rd party tools.  John doesn't have a personal need for this.
So, for now, we'll close this.  If someone really has a need for this, it can be re-opened.  In reality, a 500+ page PDF for even a medium-size IG is not likely to be useful to anyone.
