### ISSUE TITLE
Two links to the ToC in the ToC

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/ig-template-base#17]
There are two links that both go to the toc.html file in the table of contents. This seems to be the case for all IGs, which is why I suspect this is a template issue.
![image](https://user-images.githubusercontent.com/5384694/72914771-0c0bad00-3cf4-11ea-8ae4-79a6c9850c3e.png)
Suggest restructuring the ToC so that it looks like this:

* Table of Contents
* IG Home Page
  * Introduction
  * BSeR Project Team
  * ...

**Comment by lmckenzi** [comment]
The issue here is that "Table of Contents" has been put in the list of pages for the IG.  If you don't do that (and you SHOULDN'T do that), then you won't have a problem.
