### ISSUE TITLE
XSLT issues (possibly causing the publisher to crash)

### ISSUE THREAD

**Issue by vassilpeytchev** [HL7/ig-template-base#206]
in `onGenerateGrop.xslt` line 10:
```
<xsl:when test="f:resource(not(f:groupingId))">defaultgroup</xsl:when>
```
should be (?)
```
<xsl:when test="f:resource[not(f:groupingId)]">defaultgroup</xsl:when>
```
in `onGenerateGrop.xslt` line 52:
`or$infoExt` should be `or $infoExt`

in onLoad.xslt, line 94 uses parameter `single`, which is undefined. It should probably(?) be defined after line 253 as
```
<xsl:param name="single"/>
```
or removed from line 94, if it is not used.

in onGenerate.genJson.xslt, line 69 gives an error in VS Code:
```
<xsl:value-of select="concat('Unrecognized value ' + $boolean, ' for parameter ' + $property + ' - should have been Y if present')"/>
```
The following seems to be "better", for whatever reason:
```
<xsl:value-of select="concat('Unrecognized value ' + $boolean, ' for parameter ' + $property,  ' - should have been Y if present')"/>
```

**Comment by lmckenzi** [comment]
Committed
