### ISSUE TITLE
Add the ability to include an intro for StructureDefinition Mapping tabs

### ISSUE THREAD

**Issue by mvdzel** [HL7/ig-template-base#241]
Is there a way to add an intro to the StructureDefinition page Mapping tab like you can now for the Content-tab by creating an "{sd}-intro.md" file (or -notes.md for adding to the end)? 
May I suggest "StructureDefinition-{sd}-mappings-intro.md"?

**Comment by lmckenzi** [comment]
This functionality already exists as discussed on the Zulip stream.

Have updated the documentation [here](https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html#intros-and-usage-notes) to make clearer how this is done.

**Comment by mvdzel** [comment]
For me it is not clear that [suffix] can actually also be something like "mappings-intro" to add the intro to the "mappings" tab. Where is that explained?

**Comment by lmckenzi** [comment]
https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html#intros-and-usage-notes now explains this.  (It didn't previously)

**Comment by mvdzel** [comment]
I am sorry, but I don't find any mention of the tabs in the name pattern.
"The filenames for the intro and notes are [ArtifactType]-[id]-[suffix].[extension]..."
I expect some explanation that the suffix can also have additional "-mappings", or "-examples" etc. for intro and notes to the different tabs.
That is missing from the documentation now.
I now use "-mappings-intro" to add intro to only the mappings tab.
