### ISSUE TITLE
Provide link to IG itself within 'artifacts'

### ISSUE THREAD

**Issue by costateixeira** [HL7/ig-template-base#30]
The artifacts.html page (generated by the createArtifactSummary.xslt transform) should include a link to the IG artifact itself (in rendered and raw form in the different formats), probably at the top of the page.

**Comment by lmckenzi** [comment]
We're not sure if this is a good idea, or what 'rendered' views of the IG would exist for us to link to.  More exploration needed

**Comment by lmckenzi** [comment]
Now that we have the IG metadata on the home page and expectations for dependencies and globals fragment to show up, we don't see any need for this.
