### ISSUE TITLE
create default styles for new logos

### ISSUE THREAD

**Issue by costateixeira** [HL7/ig-template-base#54]
instead of family-nav, hl7-nav, etc  which only make sense in hl7 templates,
can we have in this template something like a generic set of styles like logo-nav ... or left-nav, right-nav...?
This way people can add the logos just be adding some HTML and the images, without messing with CSS

**Comment by lmckenzi** [comment]
My leaning is that each template should define its own styles for logo.  Some templates will have just one.  Da Vinci has 3.  The size, location, etc. will vary.  I don't see an issue with the template that adds the logo also appending the relevant styles to the CSS.  I do agree that the HL7 and FHIR logo-specific styles should be moved into their respective templates.

**Comment by costateixeira** [comment]
Should we put a default logo style in project.css, so that implementers that want to add a logo don't have to mess with CSS?

**Comment by lmckenzi** [comment]
They're going to want to mess with CSS to change colors anyhow.  So long as the guidance is clear, my leaning is to let them style their logos as makes sense for their logo.

**Comment by costateixeira** [comment]
With the changes to the color assignment, changing colors and add logos is now just a matter of changing some variables in a file.
People can still do CSS, but it's easier to start with something that looks decent (just one logo on the left, one on the right).
So for those cases where people just want to get up and running with an IG for their organization (and eventually change later), I think this would be very useful (and does not have any impact on existing templates).
pr #63 covers this
