### ISSUE TITLE
Create and assign new layout for Logical Models

### ISSUE THREAD

**Issue by costateixeira** [HL7/ig-template-base#57]

**Comment by costateixeira** [comment]
LMs should have their own template. 
- Display only the Snapshot tab (?)
- if there are examples for an LM, how would those be stored? and how would the publisher refer to them?
Related to issue #14

**Comment by costateixeira** [comment]
pr #62 starts this - not sure if it should be deployed already or we first fix the issues with schematrons etc.

**Comment by costateixeira** [comment]
I think this can be closed now @lmckenzi ?

**Comment by lmckenzi** [comment]
ok
