### ISSUE TITLE
remove 2nd jquery.js

### ISSUE THREAD

**Issue by costateixeira** [HL7/ig-template-base#61]
We have jquery.js in the content and in the content/assets/js folder. 
Can we remove one?

**Comment by lmckenzi** [comment]
My experience is, "no".  Removing the one in the root creates problems.  Feel free to test and explore why though...

**Comment by costateixeira** [comment]
The only place where the second jquery.js is mentioned is in the
fragment-pageend.html, line7.

I changed the reference and removed it, it and got no perceivable behaviour
change. Any critical points to test?

**Comment by lmckenzi** [comment]
I think it was the table stuff
